# Generated by Django 5.1.1 on 2024-09-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Drivers"},
        ),
    ]
